"""empty message

Revision ID: 153f4627d085
Revises: e7f7e8128f9f
Create Date: 2023-12-09 12:36:29.409552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '153f4627d085'
down_revision = 'e7f7e8128f9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agendamento', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nomeAnimal', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('nomeParceiro', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agendamento', schema=None) as batch_op:
        batch_op.drop_column('nomeParceiro')
        batch_op.drop_column('nomeAnimal')

    # ### end Alembic commands ###
