"""empty message

Revision ID: 27126600550d
Revises: 656ec0dbcf25
Create Date: 2023-12-08 03:02:47.556028

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27126600550d'
down_revision = '656ec0dbcf25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agendamento', schema=None) as batch_op:
        batch_op.alter_column('data_visita',
               existing_type=sa.VARCHAR(),
               type_=sa.Date(),
               existing_nullable=False)
        batch_op.alter_column('hora_visita',
               existing_type=sa.VARCHAR(),
               type_=sa.DateTime(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agendamento', schema=None) as batch_op:
        batch_op.alter_column('hora_visita',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
        batch_op.alter_column('data_visita',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(),
               existing_nullable=False)

    # ### end Alembic commands ###
