"""empty message

Revision ID: 3cab81b07dad
Revises: 22007d4dbb75
Create Date: 2023-12-07 17:07:36.125913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3cab81b07dad'
down_revision = '22007d4dbb75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('animal', schema=None) as batch_op:
        batch_op.drop_column('descricao_origem')
        batch_op.drop_column('origem')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('animal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('origem', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('descricao_origem', sa.VARCHAR(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
