"""empty message

Revision ID: 5fccad6e9e2c
Revises: 3cab81b07dad
Create Date: 2023-12-08 00:10:51.008974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fccad6e9e2c'
down_revision = '3cab81b07dad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ong', schema=None) as batch_op:
        batch_op.drop_column('referencia')
        batch_op.drop_column('complemento')
        batch_op.drop_column('estado')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ong', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estado', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('complemento', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('referencia', sa.VARCHAR(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
