"""empty message

Revision ID: 7b8fded9ea82
Revises: e9eb16e18d3b
Create Date: 2023-12-05 18:20:02.498408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b8fded9ea82'
down_revision = 'e9eb16e18d3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agendamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_visita', sa.String(), nullable=False),
    sa.Column('hora_visita', sa.String(), nullable=False),
    sa.Column('id_animal', sa.Integer(), nullable=True),
    sa.Column('id_parceiro', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_animal'], ['animal.id'], ),
    sa.ForeignKeyConstraint(['id_parceiro'], ['parceiro_ong.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('agendamento')
    # ### end Alembic commands ###
