"""empty message

Revision ID: 85c31770847c
Revises: 
Create Date: 2023-11-14 11:15:07.203911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85c31770847c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('animal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('especie', sa.String(), nullable=False),
    sa.Column('raca', sa.String(), nullable=False),
    sa.Column('idade', sa.Integer(), nullable=False),
    sa.Column('origem', sa.String(), nullable=False),
    sa.Column('descricao_origem', sa.String(), nullable=False),
    sa.Column('vacina_em_dia', sa.Boolean(), nullable=False),
    sa.Column('vacina', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('endereco',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('logradouro', sa.String(), nullable=False),
    sa.Column('numero', sa.String(), nullable=False),
    sa.Column('bairro', sa.String(), nullable=False),
    sa.Column('complemento', sa.String(), nullable=False),
    sa.Column('referencia', sa.String(), nullable=False),
    sa.Column('cep', sa.String(), nullable=False),
    sa.Column('cidade', sa.String(), nullable=False),
    sa.Column('estado', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pessoa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('cpf', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('senha', sa.String(), nullable=False),
    sa.Column('nascimento', sa.Date(), nullable=False),
    sa.Column('telefone', sa.String(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('telefone')
    )
    op.create_table('vacina',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ong',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('cnpj', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('senha', sa.String(), nullable=False),
    sa.Column('telefone', sa.String(), nullable=False),
    sa.Column('id_endereco', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_endereco'], ['endereco.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cnpj'),
    sa.UniqueConstraint('email')
    )
    op.create_table('parceiro_ong',
    sa.Column('id_pessoa', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_pessoa'], ['pessoa.id'], ),
    sa.PrimaryKeyConstraint('id_pessoa')
    )
    op.create_table('gestor_ong',
    sa.Column('id_pessoa', sa.Integer(), nullable=False),
    sa.Column('id_ong', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_ong'], ['ong.id'], ),
    sa.ForeignKeyConstraint(['id_pessoa'], ['pessoa.id'], ),
    sa.PrimaryKeyConstraint('id_pessoa')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gestor_ong')
    op.drop_table('parceiro_ong')
    op.drop_table('ong')
    op.drop_table('vacina')
    op.drop_table('pessoa')
    op.drop_table('endereco')
    op.drop_table('animal')
    # ### end Alembic commands ###
