"""commit

<<<<<<< HEAD:migrations/versions/e9eb16e18d3b_commit.py
Revision ID: e9eb16e18d3b
Revises: 
Create Date: 2023-12-05 17:03:32.113064
=======
Revision ID: 85c31770847c
Revises: 
Create Date: 2023-11-14 11:15:07.203911
>>>>>>> 0fce99fdcaf22548aa7eba6da32539e74b32c975:migrations/versions/85c31770847c_.py

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
<<<<<<< HEAD:migrations/versions/e9eb16e18d3b_commit.py
revision = 'e9eb16e18d3b'
=======
revision = '85c31770847c'
>>>>>>> 0fce99fdcaf22548aa7eba6da32539e74b32c975:migrations/versions/85c31770847c_.py
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('animal',
<<<<<<< HEAD:migrations/versions/e9eb16e18d3b_commit.py
=======
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('especie', sa.String(), nullable=False),
    sa.Column('raca', sa.String(), nullable=False),
    sa.Column('idade', sa.Integer(), nullable=False),
    sa.Column('origem', sa.String(), nullable=False),
    sa.Column('descricao_origem', sa.String(), nullable=False),
    sa.Column('vacina_em_dia', sa.Boolean(), nullable=False),
    sa.Column('vacina', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('endereco',
>>>>>>> 0fce99fdcaf22548aa7eba6da32539e74b32c975:migrations/versions/85c31770847c_.py
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('especie', sa.String(), nullable=False),
    sa.Column('raca', sa.String(), nullable=False),
    sa.Column('idade', sa.Integer(), nullable=False),
    sa.Column('origem', sa.String(), nullable=False),
    sa.Column('descricao_origem', sa.String(), nullable=False),
    sa.Column('vacina_em_dia', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gestor_ong',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('cpf', sa.String(), nullable=False),
    sa.Column('nascimento', sa.Date(), nullable=False),
    sa.Column('telefone', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('senha', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('telefone')
    )
    op.create_table('parceiro_ong',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('cpf', sa.String(), nullable=False),
    sa.Column('nascimento', sa.Date(), nullable=False),
    sa.Column('telefone', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('senha', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('telefone')
    )
<<<<<<< HEAD:migrations/versions/e9eb16e18d3b_commit.py
    op.create_table('relatoriodespesas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('categoria', sa.String(), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('data', sa.String(), nullable=False),
    sa.Column('observacoes', sa.String(), nullable=True),
    sa.Column('mes_Correspondente', sa.Integer(), nullable=False),
=======
    op.create_table('vacina',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
>>>>>>> 0fce99fdcaf22548aa7eba6da32539e74b32c975:migrations/versions/85c31770847c_.py
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ong',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('cnpj', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('senha', sa.String(), nullable=False),
    sa.Column('telefone', sa.String(), nullable=False),
    sa.Column('logradouro', sa.String(), nullable=False),
    sa.Column('numero', sa.String(), nullable=False),
    sa.Column('bairro', sa.String(), nullable=False),
    sa.Column('complemento', sa.String(), nullable=False),
    sa.Column('referencia', sa.String(), nullable=False),
    sa.Column('cep', sa.String(), nullable=False),
    sa.Column('cidade', sa.String(), nullable=False),
    sa.Column('estado', sa.String(), nullable=False),
    sa.Column('id_gestor', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_gestor'], ['gestor_ong.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cnpj'),
    sa.UniqueConstraint('email')
<<<<<<< HEAD:migrations/versions/e9eb16e18d3b_commit.py
=======
    )
    op.create_table('parceiro_ong',
    sa.Column('id_pessoa', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_pessoa'], ['pessoa.id'], ),
    sa.PrimaryKeyConstraint('id_pessoa')
>>>>>>> 0fce99fdcaf22548aa7eba6da32539e74b32c975:migrations/versions/85c31770847c_.py
    )
    op.create_table('vacina',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('animal_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['animal_id'], ['animal.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vacina')
    op.drop_table('ong')
<<<<<<< HEAD:migrations/versions/e9eb16e18d3b_commit.py
    op.drop_table('relatoriodespesas')
    op.drop_table('parceiro_ong')
    op.drop_table('gestor_ong')
=======
    op.drop_table('vacina')
    op.drop_table('pessoa')
    op.drop_table('endereco')
>>>>>>> 0fce99fdcaf22548aa7eba6da32539e74b32c975:migrations/versions/85c31770847c_.py
    op.drop_table('animal')
    # ### end Alembic commands ###
