"""empty message

Revision ID: 9b2243a2db0b
Revises: 936486c2db90
Create Date: 2023-10-05 01:53:58.225360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b2243a2db0b'
down_revision = '936486c2db90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('animal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('especie', sa.String(), nullable=False),
    sa.Column('raca', sa.String(), nullable=False),
    sa.Column('idade', sa.Integer(), nullable=False),
    sa.Column('origem', sa.String(), nullable=False),
    sa.Column('descricao_origem', sa.String(), nullable=False),
    sa.Column('vacina_em_dia', sa.Boolean(), nullable=False),
    sa.Column('vacina', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ong', schema=None) as batch_op:
        batch_op.drop_constraint('ong_senha_key', type_='unique')
        batch_op.drop_constraint('ong_telefone_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ong', schema=None) as batch_op:
        batch_op.create_unique_constraint('ong_telefone_key', ['telefone'])
        batch_op.create_unique_constraint('ong_senha_key', ['senha'])

    op.drop_table('animal')
    # ### end Alembic commands ###
