"""empty message

Revision ID: 9f73c7fc6e4a
Revises: 9b2243a2db0b
Create Date: 2023-10-05 02:04:35.279019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f73c7fc6e4a'
down_revision = '9b2243a2db0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vacina',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('id_animal', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_animal'], ['animal.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vacina')
    # ### end Alembic commands ###
