"""empty message

Revision ID: b0e75d39fa4b
Revises: 153f4627d085
Create Date: 2023-12-09 13:25:45.262330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0e75d39fa4b'
down_revision = '153f4627d085'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ong', schema=None) as batch_op:
        batch_op.drop_column('senha')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ong', schema=None) as batch_op:
        batch_op.add_column(sa.Column('senha', sa.VARCHAR(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
