"""empty message

Revision ID: cb148933d9f5
Revises: 9f73c7fc6e4a
Create Date: 2023-10-05 02:26:15.299226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb148933d9f5'
down_revision = '9f73c7fc6e4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vacina', schema=None) as batch_op:
        batch_op.drop_constraint('vacina_id_animal_fkey', type_='foreignkey')
        batch_op.drop_column('id_animal')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vacina', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_animal', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('vacina_id_animal_fkey', 'animal', ['id_animal'], ['id'])

    # ### end Alembic commands ###
